version: '3'
services:
  numerology_assistant:
    build:
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    image: registry365.cr.cloud.ru/numerology
    restart: always

  postgres:
    image: postgres:alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"

volumes:
  postgres_data: