version: '3'
services:
  numerology_assistant:
    build:
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    image: registry365.cr.cloud.ru/numerology:latest
    restart: always
    volumes:
      - ./numologs:/tmp/numo_magic/logs

volumes:
  numologs:
