name: Deploy to Server via SSH

on:
  workflow_run:
    workflows: ["Docker_build_and_push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Clone numo repo and copy docker-compose.yml
      uses: appleboy/ssh-action@v0.1.7
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/numomagic && git clone git@github.com:d1merz/numerology.git
            cp numerology/docker-compose.yml docker-compose.yml
            rm -r numerology
            ls -la

    - name: Run docker container
      uses: appleboy/ssh-action@v0.1.7
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/numomagic
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{secrets.DOCKER_REGISTRY}} --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker compose pull
            docker compose up -d